# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: Resume of Hamza Chowdhree
author: Hamza Chowdhree
tagline: Tech-Savvy Student
description: Resume (shortened Curriculum Vitae) 

url: "https://hamza.chowdhree.com"
baseurl: "/" 

social:
  links:
    - https://github.com/Hamy200
    - https://hamza.chowdhree.com

google_site_verification: # Put google verification tag here
google_analytics: G-7M5QP5LNSL

# End SEO

theme_skin: blue # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: 
  clippings: all
  ignore:
    envs: development
