# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: Resume of Kash Chowdhree
author: Kash Chowdhree
tagline: Cloud Solutions Architect
description: Resume (shortened Curriculum Vitae) 

url: "https://kash.chowdhree.com"
baseurl: "/resume" 

twitter:
  username: SelRE5
  card: summary

social:
  links:
    - https://twitter.com/SelRE5
    - https://www.linkedin.com/in/kash-chowdhree-34a8028
    - https://github.com/kchowdhree
    - https://kash.chowdhree.com

google_site_verification: # Put google verification tag here

# End SEO

theme_skin: blue # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: 
  clippings: all
  ignore:
    envs: development
